export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_FAIL_CONFIRM = 'AUTH_FAIL_CONFIRM';


export const FETCH_START = 'FETCH_START'; 
export const FETCH_FAIL = 'FETCH_FAIL';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const SET_FILTERS = 'SET_FILTERS';
export const UNSET_FILTERS = 'UNSET_FILTERS';

export const SHOP_MORE_FETCH_START = 'SHOP_MORE_FETCH_START';
export const SHOP_MORE_FETCH_SUCCESS_WITHOUT = 'SHOP_MORE_FETCH_SUCCESS_WITHOUT';
export const SHOP_MORE_FETCH_SUCCESS_WITH = 'SHOP_MORE_FETCH_SUCCESS_WITH';
export const SHOP_MORE_FETCH_FAIL = 'SHOP_MORE_FETCH_FAIL';

export const FETCH_SHOP_START = 'FETCH_SHOP_START';
export const FETCH_SHOP_FAIL = 'FETCH_SHOP_FAIL';
export const FETCH_SHOP_SUCCESS = 'FETCH_SHOP_SUCCESS';
export const SET_SHOP_SRCH_NAME = 'SET_SHOP_SRCH_NAME';

export const ACTIVE_CATEGORY = 'ACTIVE_CATEGORY';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';

export const ADD_CART_START = 'ADD_CART_START';
export const ADD_CART_FAIL = 'ADD_CART_FAIL';
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS';
export const CLEAR_CART_ERROR = 'CLEAR_CART_ERROR';

export const CART_OP_START = 'CART_OP_START';
export const CART_OP_FAIL = 'CART_OP_FAIL';
export const CART_ERROR_CONFIRMED = 'CART_ERROR_CONFIRMED'; 

export const CART_DEL_SUCCESS = 'CART_DEL_SUCCESS';
export const ORDER_PLACE_SUCCESS = 'ORDER_PLACE_SUCCESS';
export const ORDER_CONFIRMED = 'ORDER_CONFIRMED';
export const CLEAR_ORDERS = 'CLEAR_ORDERS';

export const CANCEL_ORDER_START = 'CANCEL_ORDER_START';
export const CANCEL_ORDER_FAIL = 'CANCEL_ORDER_FAIL';
export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS';

export const ADDRESS_OP_START = 'ADDRESS_OP_START';
export const ADDRESS_OP_FAIL = 'ADDRESS_OP_FAIL';
export const ADDRESS_OP_SUCCESS = 'ADDRESS_OP_SUCCESS';
export const ADDRESS_OP_CLEAR_ERROR = 'ADDRESS_OP_CLEAR_ERROR';

export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

export const SET = 'SET';
export const SET_TOKEN = 'SET_TOKEN'