export const shopCategories = [
  { name: 'Category*', value: 'Category*' },
  { name: 'Grocery', value: 'Grocery' },
  { name: 'Dairy', value: 'Dairy' },
  { name: 'Fashion', value: 'Fashion' },
  { name: 'Fruits & Vegetables', value: 'Fruits & Vegetables' },
  { name: 'Toys & Entertainment', value: 'Toys & Entertainment' },
  { name: 'Pharmacy', value: 'Pharmacy' },
  { name: 'Bakery', value: 'Bakery' },
  { name: 'Stationary & Books', value: 'Stationary & Books' },
  { name: 'Electronics & Accessories', value: 'Electronics & Accessories' }
];

export const states = [
  { name: 'state*', value: 'state*' },
  { name: 'Andhra Pradesh', value: 'Andhra Pradesh' },
  { name: '	Arunachal Pradesh', value: '	Arunachal Pradesh' },
  { name: '	Assam', value: '	Assam' },
  { name: 'Bihar', value: 'Bihar' },
  { name: 'Chhattisgarh', value: 'Chhattisgarh' },
  { name: '	Goa', value: '	Goa' },
  { name: 'Gujarat', value: 'Gujarat' },
  { name: 'Haryana', value: 'Haryana' },
  { name: 'Himachal Pradesh', value: 'Himachal Pradesh' },
  { name: 'Jammu and Kashmir', value: 'Jammu and Kashmir' },
  { name: 'Jharkhand	', value: 'Jharkhand	' },
  { name: 'Karnataka', value: 'Karnataka' },
  { name: 'Kerala', value: 'Kerala' },
  { name: '	Madhya Pradesh', value: '	Madhya Pradesh' },
  { name: 'Maharashtra', value: 'Maharashtra' },
  { name: '	Manipur', value: '	Manipur' },
  { name: 'Meghalaya', value: 'Meghalaya' },
  { name: 'Mizoram', value: 'Mizoram' },
  { name: 'Nagaland', value: 'Nagaland' },
  { name: 'Odisha', value: 'Odisha' },
  { name: 'Punjab', value: 'Punjab' },
  { name: 'Rajasthan', value: 'Rajasthan' },
  { name: 'Sikkim', value: 'Sikkim' },
  { name: 'Tamil Nadu', value: 'Tamil Nadu' },
  { name: 'Telangana', value: 'Telangana' },
  { name: 'Tripura', value: 'Tripura' },
  { name: 'Uttar Pradesh', value: 'Uttar Pradesh' },
  { name: 'Uttarakhand', value: 'Uttarakhand' },
  { name: 'West Bengal', value: 'West Bengal' },
];