export const AndhraPradesh = [
  // { name: 'Andhra Pradesh*', value: 'Andhra Pradesh*' },
  { name: 'district*', value: 'district*' },
  { name: 'Anantapur', value: 'Anantapur' },
  { name: 'Chittoor', value: 'Chittoor' },
  { name: 'East Godavari', value: 'East Godavari' },
  { name: 'Guntur', value: 'Guntur' },
  { name: 'Kadapa', value: 'Kadapa' },
  { name: 'Krishna', value: 'Krishna' },
  { name: 'Kurnool', value: 'Kurnool' },
  { name: 'Prakasam', value: 'Prakasam' },
  { name: 'Sri Potti Sriramulu Nellore', value: 'Sri Potti Sriramulu Nellore' },
  { name: 'Srikakulam', value: 'Srikakulam' },
  { name: 'Visakhapatnam', value: 'Visakhapatnam' },
  { name: 'Vizianagaram', value: 'Vizianagaram' },
  { name: 'West Godavari', value: 'West Godavari' },
];

export const ArunachalPradesh = [
  // { name: '*Arunachal Pradesh', value: '*Arunachal Pradesh' },
  { name: 'district*', value: 'district*' },
  { name: 'Anjaw', value: 'Anjaw' },
  { name: 'Changlang', value: 'Changlang' },
  { name: 'Dibang Valley', value: 'Dibang Valley' },
  { name: 'East Kameng', value: 'East Kameng' },
  { name: 'East Siang', value: 'East Siang' },
  { name: 'Kamle', value: 'Kamle' },
  { name: 'Kra Daadi', value: 'Kra Daadi' },
  { name: 'Kurung Kumey', value: 'Kurung Kumey' },
  { name: 'Lepa Rada', value: 'Lepa Rada' },
  { name: 'Lohit', value: 'Lohit' },
  { name: 'Longding', value: 'Longding' },
  { name: 'Lower Dibang Valley', value: 'Lower Dibang Valley' },
  { name: 'Lower Subansiri', value: 'Lower Subansiri' },
  { name: 'Namsai', value: 'Namsai' },
  { name: 'Pakke Kessang', value: 'Pakke Kessang' },
  { name: 'Papum Pare', value: 'Papum Pare' },
  { name: 'Shi Yomi', value: 'Shi Yomi' },
  { name: 'Siang', value: 'Siang' },
  { name: 'Tawang', value: 'Tawang' },
  { name: 'Tirap', value: 'Tirap' },
  { name: 'Upper Siang', value: 'Upper Siang' },
  { name: 'Upper Subansiri', value: 'Upper Subansiri' },
  { name: 'West Kameng', value: 'West Kameng' },
  { name: 'West Siang', value: 'West Siang' },
];

export const Assam = [
  // { name: '*Assam', value: '*Assam' },
  { name: 'district*', value: 'district*' },
  { name: 'Baksa', value: 'Baksa' },
  { name: 'Barpeta', value: 'Barpeta' },
  { name: 'Biswanath', value: 'Biswanath' },
  { name: 'Bongaigaon', value: 'Bongaigaon' },
  { name: 'Cachar', value: 'Cachar' },
  { name: 'Cachar', value: 'Cachar' },
  { name: 'Charaideo', value: 'Charaideo' },
  { name: 'Chirang', value: 'Chirang' },
  { name: 'Darrang', value: 'Darrang' },
  { name: 'Dhemaji', value: 'Dhemaji' },
  { name: 'Dhubri', value: 'Dhubri' },
  { name: 'Dibrugarh', value: 'Dibrugarh' },
  { name: 'Dima Hasao', value: 'Dima Hasao' },
  { name: 'Goalpara', value: 'Goalpara' },
  { name: 'Golaghat', value: 'Golaghat' },
  { name: 'Hailakandi', value: 'Hailakandi' },
  { name: 'Hojai', value: 'Hojai' },
  { name: 'Jorhat', value: 'Jorhat' },
  { name: 'Kamrup', value: 'Kamrup' },
  { name: 'Kamrup Metropolitan', value: 'Kamrup Metropolitan' },
  { name: 'Karbi Anglong', value: 'Karbi Anglong' },
  { name: 'Karimganj', value: 'Karimganj' },
  { name: 'Kokrajhar', value: 'Kokrajhar' },
  { name: 'Lakhimpur', value: 'Lakhimpur' },
  { name: 'Majuli', value: 'Majuli' },
  { name: 'Morigaon', value: 'Morigaon' },
  { name: 'Nagaon', value: 'Nagaon' },
  { name: 'Nalbari', value: 'Nalbari' },
  { name: 'Sivasagar', value: 'Sivasagar' },
  { name: 'Sonitpur', value: 'Sonitpur' },
  { name: 'South Salamara-Mankachar', value: 'South Salamara-Mankachar' },
  { name: 'Tinsukia', value: 'Tinsukia' },
  { name: 'Udalguri', value: 'Udalguri' },
  { name: 'West Karbi Anglong', value: 'West Karbi Anglong' },
];

export const Bihar = [
  // { name: '*Bihar', value: '*Bihar' },
  { name: 'district*', value: 'district*' },
  { name: 'Araria', value: 'Araria' },
  { name: 'Arwal', value: 'Arwal' },
  { name: 'Aurangabad', value: 'Aurangabad' },
  { name: 'Banka', value: 'Banka' },
  { name: 'Begusarai', value: 'Begusarai' },
  { name: 'Bhagalpur', value: 'Bhagalpur' },
  { name: 'Bhojpur', value: 'Bhojpur' },
  { name: 'Buxar', value: 'Buxar' },
  { name: 'Darbhanga', value: 'Darbhanga' },
  { name: 'East Champaran', value: 'East Champaran' },
  { name: 'Gaya', value: 'Gaya' },
  { name: 'Gopalganj', value: 'Gopalganj' },
  { name: 'Jamui', value: 'Jamui' },
  { name: 'Jehanabad', value: 'Jehanabad' },
  { name: 'Kaimur', value: 'Kaimur' },
  { name: 'Katihar', value: 'Katihar' },
  { name: 'Khagaria', value: 'Khagaria' },
  { name: 'Kishanganj', value: 'Kishanganj' },
  { name: 'Lakhisarai', value: 'Lakhisarai' },
  { name: 'Madhepura', value: 'Madhepura' },
  { name: 'Madhubani', value: 'Madhubani' },
  { name: 'Monghyr', value: 'Monghyr' },
  { name: 'Muzaffarpur', value: 'Muzaffarpur' },
  { name: 'Nalanda', value: 'Nalanda' },
  { name: 'Nawada', value: 'Nawada' },
  { name: 'Patna', value: 'Patna' },
  { name: 'Purnea', value: 'Purnea' },
  { name: 'Rohtas', value: 'Rohtas' },
  { name: 'Saharsa', value: 'Saharsa' },
  { name: 'Samastipur', value: 'Samastipur' },
  { name: 'Saran', value: 'Saran' },
  { name: 'Sheikhpura', value: 'Sheikhpura' },
  { name: 'Sheohar', value: 'Sheohar' },
  { name: 'Sitamarhi', value: 'Sitamarhi' },
  { name: 'Siwan', value: 'Siwan' },
  { name: 'Supaul', valueSitamarhi: 'Supaul' },
  { name: 'Vaishali', value: 'Vaishali' },
  { name: 'West Champaran', value: 'West Champaran' },
];

export const Chhattisgarh = [
  // { name: '*Chhattisgarh', value: '*Chhattisgarh' },
  { name: 'district*', value: 'district*' },
  { name: 'Balod', value: 'Balod' },
  { name: 'Baloda Bazar', value: 'Baloda Bazar' },
  { name: 'Balrampur', value: 'Balrampur' },
  { name: 'Bastar', value: 'Bastar' },
  { name: 'Bemetara', value: 'Bemetara' },
  { name: 'Bijapur', value: 'Bijapur' },
  { name: 'Bilaspur', value: 'Bilaspur' },
  { name: 'Dantewada', value: 'Dantewada' },
  { name: 'Dhamtari', value: 'Dhamtari' },
  { name: 'Durg', value: 'Durg' },
  { name: 'Gariaband', value: 'Gariaband' },
  { name: 'Janjgir-Champa', value: 'Janjgir-Champa' },
  { name: 'Jashpur', value: 'Jashpur' },
  { name: 'Kawardha', value: 'Kawardha' },
  { name: 'Kanker', value: 'Kanker' },
  { name: 'Kondagaon', value: 'Kondagaon' },
  { name: 'Korba', value: 'Korba' },
  { name: 'Korea', value: 'Korea' },
  { name: 'Mahasamund', value: 'Mahasamund' },
  { name: 'Mungeli', value: 'Mungeli' },
  { name: 'Narayanpur', value: 'Narayanpur' },
  { name: 'Raigarh', value: 'Raigarh' },
  { name: 'Raipur', value: 'Raipur' },
  { name: 'Rajnandgaon', value: 'Rajnandgaon' },
  { name: 'Sukma', value: 'Sukma' },
  { name: 'Surajpur', value: 'Surajpur' },
  { name: 'Surguja', value: 'Surguja' },
];

export const Goa = [
  // { name: '*Goa', value: '*Goa' },
  { name: 'district*', value: 'district*' },
  { name: 'North Goa', value: 'North Goa' },
  { name: 'South Goa', value: 'South Goa' },
];

export const Gujarat = [
  // { name: '*Gujarat', value: '*Gujarat' },
  { name: 'district*', value: 'district*' },
  { name: 'Ahmedabad', value: 'Ahmedabad' },
  { name: 'Amreli', value: 'Amreli' },
  { name: 'Anand', value: 'Anand' },
  { name: 'Aravalli', value: 'Aravalli' },
  { name: 'Banaskantha', value: 'Banaskantha' },
  { name: 'Bharuch', value: 'Bharuch' },
  { name: 'Bhavnagar', value: 'Bhavnagar' },
  { name: 'Botad', value: 'Botad' },
  { name: 'Chhota Udepur', value: 'Chhota Udepur' },
  { name: 'Dahod', value: 'Dahod' },
  { name: 'Dang', value: 'Dang' },
  { name: 'Devbhoomi Dwarka', value: 'Devbhoomi Dwarka' },
  { name: 'Gandhinagar', value: 'Gandhinagar' },
  { name: 'Gir Somnath', value: 'Gir Somnath' },
  { name: 'Jamnagar', value: 'Jamnagar' },
  { name: 'Junagadh', value: 'Junagadh' },
  { name: 'Kutch', value: 'Kutch' },
  { name: 'Kheda', value: 'Kheda' },
  { name: 'Mahisagar', value: 'Mahisagar' },
  { name: 'Mehsana', value: 'Mehsana' },
  { name: 'Morbi', vKhedaue: 'Morbi' },
  { name: 'Narmada', value: 'Narmada' },
  { name: 'Navsari', value: 'Navsari' },
  { name: 'Panchmahal', value: 'Panchmahal' },
  { name: 'Patan', value: 'Patan' },
  { name: 'Porbandar', value: 'Porbandar' },
  { name: 'Rajkot', value: 'Rajkot' },
  { name: 'Sabarkantha', value: 'Sabarkantha' },
  { name: 'Surat', value: 'Surat' },
  { name: 'Surendranagar', value: 'Surendranagar' },
  { name: 'Tapi', value: 'Tapi' },
  { name: 'Vadodara', value: 'Vadodara' },
  { name: 'Valsad', value: 'Valsad' },
];

export const Haryana = [
  // { name: '*Haryana', value: '*Haryana' },
  { name: 'district*', value: 'district*' },
  { name: 'Ambala', value: 'Ambala' },
  { name: 'Bhiwani', value: 'Bhiwani' },
  { name: 'Charkhi Dadri', value: 'Charkhi Dadri' },
  { name: 'Faridabad', value: 'Faridabad' },
  { name: 'Fatehabad', value: 'Fatehabad' },
  { name: 'Gurgaon', value: 'Gurgaon' },
  { name: 'Hisar', value: 'Hisar' },
  { name: 'Jhajjar', value: 'Jhajjar' },
  { name: 'Jind', value: 'Jind' },
  { name: 'Kaithal', value: 'Kaithal' },
  { name: 'Karnal', value: 'Karnal' },
  { name: 'Kurukshetra', value: 'Kurukshetra' },
  { name: 'Mahendragarh', value: 'Mahendragarh' },
  { name: 'Mewat', value: 'Mewat' },
  { name: 'Palwal', value: 'Palwal' },
  { name: 'Panchkula', value: 'Panchkula' },
  { name: 'Panipat', value: 'Panipat' },
  { name: 'Rewari', value: 'Rewari' },
  { name: 'Rohtak', value: 'Rohtak' },
  { name: 'Sirsa', value: 'Sirsa' },
  { name: 'Sonipat', value: 'Sonipat' },
  { name: 'Yamunanagar', value: 'Yamunanagar' },
];

export const HimachalPradesh = [
  // { name: '*HimachalPradesh', value: '*HimachalPradesh' },
  { name: 'district*', value: 'district*' },
  { name: 'Bilaspur', value: 'Bilaspur' },
  { name: 'Chamba', value: 'Chamba' },
  { name: 'Hamirpur', value: 'Hamirpur' },
  { name: 'Kangra', value: 'Kangra' },
  { name: 'Kinnaur', value: 'Kinnaur' },
  { name: 'Kullu', value: 'Kullu' },
  { name: 'Lahaul & Spiti', value: 'Lahaul & Spiti' },
  { name: 'Mandi', value: 'Mandi' },
  { name: 'Shimla', value: 'Shimla' },
  { name: 'Sirmaur', value: 'Sirmaur' },
  { name: 'Solan', value: 'Solan' },
  { name: 'Una', value: 'Una' },
];

export const JammuandKashmir = [
  // { name: '*Jammu and Kashmir', value: '*Jammu and Kashmir' },
  { name: 'district*', value: 'district*' },
  { name: 'Anantnag', value: 'Anantnag' },
  { name: 'Bandipore', value: 'Bandipore' },
  { name: 'Baramulla', value: 'Baramulla' },
  { name: 'Budgam', value: 'Budgam' },
  { name: 'Doda', value: 'Doda' },
  { name: 'Ganderbal', value: 'Ganderbal' },
  { name: 'Jammu', value: 'Jammu' },
  { name: 'Kathua', value: 'Kathua' },
  { name: 'Kargil', value: 'Kargil' },
  { name: 'Kishtwar', value: 'Kishtwar' },
  { name: 'Kulgam', value: 'Kulgam' },
  { name: 'Kupwara', value: 'Kupwara' },
  { name: 'Leh', value: 'Leh' },
  { name: 'Poonch', value: 'Poonch' },
  { name: 'Pulwama', value: 'Pulwama' },
  { name: 'Ramban', value: 'Ramban' },
  { name: 'Reasi', value: 'Reasi' },
  { name: 'Rajouri', value: 'Rajouri' },
  { name: 'Samba', value: 'Samba' },
  { name: 'Shopian', value: 'Shopian' },
  { name: 'Srinagar', value: 'Srinagar' },
  { name: 'Udhampur', value: 'Udhampur' },
];

export const Jharkhand = [
  // { name: '*Jharkhand', value: '*Jharkhand' },
  { name: 'district*', value: 'district*' },
  { name: 'Bokaro', value: 'Bokaro' },
  { name: 'Chatra', value: 'Chatra' },
  { name: 'Deoghar', value: 'Deoghar' },
  { name: 'Dhanbad', value: 'Dhanbad' },
  { name: 'Dumka', value: 'Dumka' },
  { name: 'East Singhbhum', value: 'East Singhbhum' },
  { name: 'Garhwa', value: 'Garhwa' },
  { name: 'Giridih', value: 'Giridih' },
  { name: 'Godda', value: 'Godda' },
  { name: 'Gumla', value: 'Gumla' },
  { name: 'Hazaribagh', value: 'Hazaribagh' },
  { name: 'Jamtara', value: 'Jamtara' },
  { name: 'Khunti', value: 'Khunti' },
  { name: 'Koderma', value: 'Koderma' },
  { name: 'Latehar', value: 'Latehar' },
  { name: 'Lohardaga', value: 'Lohardaga' },
  { name: 'Pakur', value: 'Pakur' },
  { name: 'Palamu', value: 'Palamu' },
  { name: 'Ramgarh', value: 'Ramgarh' },
  { name: 'Ranchi', value: 'Ranchi' },
  { name: 'Sahibganj', value: 'Sahibganj' },
  { name: 'Seraikella Kharsawan', value: 'Seraikella Kharsawan' },
  { name: 'Simdega', value: 'Simdega' },
  { name: 'West Singhbhum', value: 'West Singhbhum' },
];

export const Karnataka = [
  // { name: '*Karnataka', value: '*Karnataka' },
  { name: 'district*', value: 'district*' },
  { name: 'Bagalkot', value: 'Bagalkot' },
  { name: 'Ballari', value: 'Ballari' },
  { name: 'Belagavi', value: 'Belagavi' },
  { name: 'Bengaluru Rural', value: 'Bengaluru Rural' },
  { name: 'Bengaluru Urban', value: 'Bengaluru Urban' },
  { name: 'Bidar', value: 'Bidar' },
  { name: 'Chamarajanagar', value: 'Chamarajanagar' },
  { name: 'Chikballapur', value: 'Chikballapur' },
  { name: 'Chikkamagaluru', value: 'Chikkamagaluru' },
  { name: 'Chitradurga', value: 'Chitradurga' },
  { name: 'Dakshina Kannada', value: 'Dakshina Kannada' },
  { name: 'Davangere', value: 'Davangere' },
  { name: 'Dharwad', value: 'Dharwad' },
  { name: 'Gadag', value: 'Gadag' },
  { name: 'Hassan', value: 'Hassan' },
  { name: 'Haveri', value: 'Haveri' },
  { name: 'Kalaburagi', value: 'Kalaburagi' },
  { name: 'Kodagu', value: 'Kodagu' },
  { name: 'Kolar', value: 'Kolar' },
  { name: 'Koppal', value: 'Koppal' },
  { name: 'Mandya', value: 'Mandya' },
  { name: 'Mysuru', value: 'Mysuru' },
  { name: 'Raichur', value: 'Raichur' },
  { name: 'Ramanagara', value: 'Ramanagara' },
  { name: 'Shivamogga', value: 'Shivamogga' },
  { name: 'Tumakuru', value: 'Tumakuru' },
  { name: 'Udupi', value: 'Udupi' },
  { name: 'Uttara Kannada', value: 'Uttara Kannada' },
  { name: 'Vijayapura', value: 'Vijayapura' },
  { name: 'Yadgir', value: 'Yadgir' },
];

export const Kerala = [
  // { name: '*Kerala', value: '*Kerala' },
  { name: 'district*', value: 'district*' },
  { name: 'Alappuzha', value: 'Alappuzha' },
  { name: 'Ernakulam', value: 'Ernakulam' },
  { name: 'Idukki', value: 'Idukki' },
  { name: 'Kannur', value: 'Kannur' },
  { name: 'Kasaragod', value: 'Kasaragod' },
  { name: 'Kollam', value: 'Kollam' },
  { name: 'Kottayam', value: 'Kottayam' },
  { name: 'Kozhikode', value: 'Kozhikode' },
  { name: 'Malappuram', value: 'Malappuram' },
  { name: 'Palakkad', value: 'Palakkad' },
  { name: 'Pathanamthitta', value: 'Pathanamthitta' },
  { name: 'Thiruvananthapuram', value: 'Thiruvananthapuram' },
  { name: 'Thrissur', value: 'Thrissur' },
  { name: 'Wayanad', value: 'Wayanad' },
];

export const MadhyaPradesh = [
  // { name: '*Madhya Pradesh', value: '*Madhya Pradesh' },
  { name: 'district*', value: 'district*' },
  { name: 'Agar Malwa', value: 'Agar Malwa' },
  { name: 'Alirajpur', value: 'Alirajpur' },
  { name: 'Anuppur', value: 'Anuppur' },
  { name: 'Ashoknagar', value: 'Ashoknagar' },
  { name: 'Balaghat', value: 'Balaghat' },
  { name: 'Barwani', value: 'Barwani' },
  { name: 'Betul', value: 'Betul' },
  { name: 'Bhind', value: 'Bhind' },
  { name: 'Bhopal', value: 'Bhopal' },
  { name: 'Burhanpur', value: 'Burhanpur' },
  { name: 'Chhatarpur', value: 'Chhatarpur' },
  { name: 'Chhindwara', value: 'Chhindwara' },
  { name: 'Damoh', value: 'Damoh' },
  { name: 'Datia', value: 'Datia' },
  { name: 'Dewas', value: 'Dewas' },
  { name: 'Dhar', value: 'Dhar' },
  { name: 'Dindori', value: 'Dindori' },
  { name: 'Guna', value: 'Guna' },
  { name: 'Gwalior', value: 'Gwalior' },
  { name: 'Harda', value: 'Harda' },
  { name: 'Hoshangabad', value: 'Hoshangabad' },
  { name: 'Indore', value: 'Indore' },
  { name: 'Jabalpur', value: 'Jabalpur' },
  { name: 'Jhabua', value: 'Jhabua' },
  { name: 'Katni', value: 'Katni' },
  { name: 'Khandwa', value: 'Khandwa' },
  { name: 'Khargone', value: 'Khargone' },
  { name: 'Mandla', value: 'Mandla' },
  { name: 'Mandsaur', value: 'Mandsaur' },
  { name: 'Morena', value: 'Morena' },
  { name: 'Narsinghpur', value: 'Narsinghpur' },
  { name: 'Neemuch', value: 'Neemuch' },
  { name: 'Panna', value: 'Panna' },
  { name: 'Raisen', value: 'Raisen' },
  { name: 'Rajgarh', value: 'Rajgarh' },
  { name: 'Ratlam', value: 'Ratlam' },
  { name: 'Rewa', value: 'Rewa' },
  { name: 'Sagar', value: 'Sagar' },
  { name: 'Satna', value: 'Satna' },
  { name: 'Sehore', value: 'Sehore' },
  { name: 'Seoni', value: 'Seoni' },
  { name: 'Shahdol', value: 'Shahdol' },
  { name: 'Shajapur', value: 'Shajapur' },
  { name: 'Sheopur', value: 'Sheopur' },
  { name: 'Shivpuri', value: 'Shivpuri' },
  { name: 'Sidhi', value: 'Sidhi' },
  { name: 'Singrauli', value: 'Singrauli' },
  { name: 'Tikamgarh', value: 'Tikamgarh' },
  { name: 'Ujjain', value: 'Ujjain' },
  { name: 'Umaria', value: 'Umaria' },
  { name: 'Vidisha', value: 'Vidisha' },
];

export const Maharashtra = [
  // { name: '*Maharashtra', value: '*Maharashtra' },
  { name: 'district*', value: 'district*' },
  { name: 'Ahmednagar', value: 'Ahmednagar' },
  { name: 'Akola', value: 'Akola' },
  { name: 'Amravati', value: 'Amravati' },
  { name: 'Aurangabad', value: 'Aurangabad' },
  { name: 'Beed', value: 'Beed' },
  { name: 'Bhandara', value: 'Bhandara' },
  { name: 'Buldhana', value: 'Buldhana' },
  { name: 'Chandrapur', value: 'Chandrapur' },
  { name: 'Dhule', value: 'Dhule' },
  { name: 'Gadchiroli', value: 'Gadchiroli' },
  { name: 'Gondia', value: 'Gondia' },
  { name: 'Hingoli', value: 'Hingoli' },
  { name: 'Jalgaon', value: 'Jalgaon' },
  { name: 'Jalna', value: 'Jalna' },
  { name: 'Kolhapur', value: 'Kolhapur' },
  { name: 'Latur', value: 'Latur' },
  { name: 'Mumbai City', value: 'Mumbai City' },
  { name: 'Mumbai Suburban', value: 'Mumbai Suburban' },
  { name: 'Nagpur', value: 'Nagpur' },
  { name: 'Nanded', value: 'Nanded' },
  { name: 'Nandurbar', value: 'Nandurbar' },
  { name: 'Nashik', value: 'Nashik' },
  { name: 'Osmanabad', value: 'Osmanabad' },
  { name: 'Palghar', value: 'Palghar' },
  { name: 'Parbhani', value: 'Parbhani' },
  { name: 'Pune', value: 'Pune' },
  { name: 'Raigad', value: 'Raigad' },
  { name: 'Ratnagiri', value: 'Ratnagiri' },
  { name: 'Sangli', value: 'Sangli' },
  { name: 'Satara', value: 'Satara' },
  { name: 'Sindhudurg', value: 'Sindhudurg' },
  { name: 'Solapur', value: 'Solapur' },
  { name: 'Thane', value: 'Thane' },
  { name: 'Wardha', value: 'Wardha' },
  { name: 'Washim', value: 'Washim' },
  { name: 'Yavatmal', value: 'Yavatmal' },
];

export const Manipur = [
  // { name: '*Manipur', value: '*Manipur' },
  { name: 'district*', value: 'district*' },
  { name: 'Bishnupur', value: 'Bishnupur' },
  { name: 'Chandel', value: 'Chandel' },
  { name: 'Churachandpur', value: 'Churachandpur' },
  { name: 'Imphal-East', value: 'Imphal-East' },
  { name: 'Imphal-West', value: 'Imphal-West' },
  { name: 'Jiribam', value: 'Jiribam' },
  { name: 'Kakching', value: 'Kakching' },
  { name: 'Kamjong', value: 'Kamjong' },
  { name: 'Kangpokpi', value: 'Kangpokpi' },
  { name: 'Noney', value: 'Noney' },
  { name: 'Pherzawl', value: 'Pherzawl' },
  { name: 'Senapati', value: 'Senapati' },
  { name: 'Tamenglong', value: 'Tamenglong' },
  { name: 'Tengnoupal', value: 'Tengnoupal' },
  { name: 'Thoubal', value: 'Thoubal' },
  { name: 'Ukhrul', value: 'Ukhrul' },
];

export const Meghalaya = [
  // { name: '*Meghalaya', value: '*Meghalaya' },
  { name: 'district*', value: 'district*' },
  { name: 'East Garo Hills', value: 'East Garo Hills' },
  { name: 'East Jaintia Hills', value: 'East Jaintia Hills' },
  { name: 'East Khasi Hills', value: 'East Khasi Hills' },
  { name: 'North Garo Hills', value: 'North Garo Hills' },
  { name: 'Ri Bhoi', value: 'Ri Bhoi' },
  { name: 'South Garo Hills', value: 'South Garo Hills' },
  { name: 'South West Garo Hills', value: 'South West Garo Hills' },
  { name: 'South West Khasi Hills', value: 'South West Khasi Hills' },
  { name: 'West Garo Hills', value: 'West Garo Hills' },
  { name: 'West Jaintia Hills', value: 'West Jaintia Hills' },
  { name: 'West Khasi Hills', value: 'West Khasi Hills' },
];

export const Mizoram = [
  // { name: '*Mizoram', value: '*Mizoram' },
  { name: 'district*', value: 'district*' },
  { name: 'Aizawl', value: 'Aizawl' },
  { name: 'Champhai', value: 'Champhai' },
  { name: 'Kolasib', value: 'Kolasib' },
  { name: 'Lawngtlai', value: 'Lawngtlai' },
  { name: 'Lunglei', value: 'Lunglei' },
  { name: 'Mamit', value: 'Mamit' },
  { name: 'Saiha', value: 'Saiha' },
  { name: 'Serchhip', value: 'Serchhip' },
];

export const Nagaland = [
  // { name: '*Nagaland', value: '*Nagaland' },
  { name: 'district*', value: 'district*' },
  { name: 'Dimapur', value: 'Dimapur' },
  { name: 'Kiphire', value: 'Kiphire' },
  { name: 'Kohima', value: 'Kohima' },
  { name: 'Longleng', value: 'Longleng' },
  { name: 'Mokokchung', value: 'Mokokchung' },
  { name: 'Mon', value: 'Mon' },
  { name: 'Peren', value: 'Peren' },
  { name: 'Phek', value: 'Phek' },
  { name: 'Tuensang', value: 'Tuensang' },
  { name: 'Wokha', value: 'Wokha' },
  { name: 'Zunheboto', value: 'Zunheboto' },
];

export const Odisha = [
  // { name: '*Odisha', value: '*Odisha' },
  { name: 'district*', value: 'district*' },
  { name: 'Angul', value: 'Angul' },
  { name: 'Balangir', value: 'Balangir' },
  { name: 'Balasore', value: 'Balasore' },
  { name: 'Bargarh', value: 'Bargarh' },
  { name: 'Bhadrak', value: 'Bhadrak' },
  { name: 'Boudh', value: 'Boudh' },
  { name: 'Cuttack', value: 'Cuttack' },
  { name: 'Deogarh', value: 'Deogarh' },
  { name: 'Dhenkanal', value: 'Dhenkanal' },
  { name: 'Gajapati', value: 'Gajapati' },
  { name: 'Ganjam', value: 'Ganjam' },
  { name: 'Jagatsinghapur', value: 'Jagatsinghapur' },
  { name: 'Jajpur', value: 'Jajpur' },
  { name: 'Jharsuguda', value: 'Jharsuguda' },
  { name: 'Kalahandi', value: 'Kalahandi' },
  { name: 'Kandhamal', value: 'Kandhamal' },
  { name: 'Kendrapara', value: 'Kendrapara' },
  { name: 'Keonjhar', value: 'Keonjhar' },
  { name: 'Khurda', value: 'Khurda' },
  { name: 'Koraput', value: 'Koraput' },
  { name: 'Malkangiri', value: 'Malkangiri' },
  { name: 'Mayurbhanj', value: 'Mayurbhanj' },
  { name: 'Nabarangpur', value: 'Nabarangpur' },
  { name: 'Nayagarh', value: 'Nayagarh' },
  { name: 'Nuapada', value: 'Nuapada' },
  { name: 'Puri', value: 'Puri' },
  { name: 'Rayagada', value: 'Rayagada' },
  { name: 'Sambalpur', value: 'Sambalpur' },
  { name: 'Sonepur', value: 'Sonepur' },
  { name: 'Sundargarh', value: 'Sundargarh' },
];

export const Punjab = [
  // { name: '*Punjab', value: '*Punjab' },
  { name: 'district*', value: 'district*' },
  { name: 'Amritsar', value: 'Amritsar' },
  { name: 'Barnala', value: 'Barnala' },
  { name: 'Bathinda', value: 'Bathinda' },
  { name: 'Faridkot', value: 'Faridkot' },
  { name: 'Fatehgarh Sahib', value: 'Fatehgarh Sahib' },
  { name: 'Fazilka', value: 'Fazilka' },
  { name: 'Ferozepur', value: 'Ferozepur' },
  { name: 'Gurdaspur', value: 'Gurdaspur' },
  { name: 'Hoshiarpur', value: 'Hoshiarpur' },
  { name: 'Jalandhar', value: 'Jalandhar' },
  { name: 'Kapurthala', value: 'Kapurthala' },
  { name: 'Ludhiana', value: 'Ludhiana' },
  { name: 'Mansa', value: 'Mansa' },
  { name: 'Moga', value: 'Moga' },
  { name: 'Muktsar', value: 'Muktsar' },
  { name: 'Pathankot', value: 'Pathankot' },
  { name: 'Patiala', value: 'Patiala' },
  { name: 'Rupnagar', value: 'Rupnagar' },
  { name: 'Sahibzada Ajit Singh Nagar', value: 'Sahibzada Ajit Singh Nagar' },
  { name: 'Sangrur', value: 'Sangrur' },
  { name: 'Shahid Bhagat Singh Nagar', value: 'Shahid Bhagat Singh Nagar' },
  { name: 'Tarn Taran', value: 'Tarn Taran' },
];

export const Rajasthan = [
  // { name: '*Rajasthan', value: '*Rajasthan' },
  { name: 'district*', value: 'district*' },
  { name: 'Ajmer', value: 'Ajmer' },
  { name: 'Alwar', value: 'Alwar' },
  { name: 'Banswara', value: 'Banswara' },
  { name: 'Baran', value: 'Baran' },
  { name: 'Barmer', value: 'Barmer' },
  { name: 'Bharatpur', value: 'Bharatpur' },
  { name: 'Bhilwara', value: 'Bhilwara' },
  { name: 'Bikaner', value: 'Bikaner' },
  { name: 'Bundi', value: 'Bundi' },
  { name: 'Chittorgarh', value: 'Chittorgarh' },
  { name: 'Churu', value: 'Churu' },
  { name: 'Dausa', value: 'Dausa' },
  { name: 'Dholpur', value: 'Dholpur' },
  { name: 'Dungarpur', value: 'Dungarpur' },
  { name: 'Hanumangarh', value: 'Hanumangarh' },
  { name: 'Jaipur', value: 'Jaipur' },
  { name: 'Jaisalmer', value: 'Jaisalmer' },
  { name: 'Jalore', value: 'Jalore' },
  { name: 'Jhalawar', value: 'Jhalawar' },
  { name: 'Jhunjhunu', value: 'Jhunjhunu' },
  { name: 'Jodhpur', value: 'Jodhpur' },
  { name: 'Karauli', value: 'Karauli' },
  { name: 'Kota', value: 'Kota' },
  { name: 'Nagaur', value: 'Nagaur' },
  { name: 'Pali', value: 'Pali' },
  { name: 'Pratapgarh', value: 'Pratapgarh' },
  { name: 'Rajsamand', value: 'Rajsamand' },
  { name: 'Sawai Madhopur', value: 'Sawai Madhopur' },
  { name: 'Sikar', value: 'Sikar' },
  { name: 'Sirohi', value: 'Sirohi' },
  { name: 'Sri Ganganagar', value: 'Sri Ganganagar' },
  { name: 'Tonk', value: 'Tonk' },
  { name: 'Udaipur', value: 'Udaipur' },
];

export const Sikkim = [
  // { name: '*Sikkim', value: '*Sikkim' },
  { name: 'district*', value: 'district*' },
  { name: 'East Sikkim', value: 'East Sikkim' },
  { name: 'North Sikkim', value: 'North Sikkim' },
  { name: 'South Sikkim', value: 'South Sikkim' },
  { name: 'West Sikkim', value: 'West Sikkim' },
];

export const TamilNadu = [
  // { name: '*Tamil Nadu', value: '*Tamil Nadu' },
  { name: 'district*', value: 'district*' },
  { name: 'Ariyalur', value: 'Ariyalur' },
  { name: 'Chennai', value: 'Chennai' },
  { name: 'Coimbatore', value: 'Coimbatore' },
  { name: 'Cuddalore', value: 'Cuddalore' },
  { name: 'Dharmapuri', value: 'Dharmapuri' },
  { name: 'Dindigul', value: 'Dindigul' },
  { name: 'Erode', value: 'Erode' },
  { name: 'Kanchipuram', value: 'Kanchipuram' },
  { name: 'Kanyakumari', value: 'Kanyakumari' },
  { name: 'Karur', value: 'Karur' },
  { name: 'Krishnagiri', value: 'Krishnagiri' },
  { name: 'Madurai', value: 'Madurai' },
  { name: 'Nagapattinam', value: 'Nagapattinam' },
  { name: 'Namakkal', value: 'Namakkal' },
  { name: 'Perambalur', value: 'Perambalur' },
  { name: 'Pudukkottai', value: 'Pudukkottai' },
  { name: 'Ramanathapuram', value: 'Ramanathapuram' },
  { name: 'Salem', value: 'Salem' },
  { name: 'Sivaganga', value: 'Sivaganga' },
  { name: 'Thanjavur', value: 'Thanjavur' },
  { name: 'The Nilgiris', value: 'The Nilgiris' },
  { name: 'Theni', value: 'Theni' },
  { name: 'Thiruvallur', value: 'Thiruvallur' },
  { name: 'Thiruvarur', value: 'Thiruvarur' },
  { name: 'Thoothukudi', value: 'Thoothukudi' },
  { name: 'Tiruchirappalli', value: 'Tiruchirappalli' },
  { name: 'Tirunelveli', value: 'Tirunelveli' },
  { name: 'Tirupur', value: 'Tirupur' },
  { name: 'Tiruvannamalai', value: 'Tiruvannamalai' },
  { name: 'Vellore', value: 'Vellore' },
  { name: 'Viluppuram', value: 'Viluppuram' },
  { name: 'Virudhunagar', value: 'Virudhunagar' },
];

export const Telangana = [
  // { name: '*Telangana', value: '*Telangana' },
  { name: 'district*', value: 'district*' },
  { name: 'Adilabad', value: 'Adilabad' },
  { name: 'Bhadradri Kothagudem', value: 'Bhadradri Kothagudem' },
  { name: 'Hyderabad', value: 'Hyderabad' },
  { name: 'Jagtial', value: 'Jagtial' },
  { name: 'Jangaon', value: 'Jangaon' },
  { name: 'Jayashankar Bhupalpally', value: 'Jayashankar Bhupalpally' },
  { name: 'Jogulamba Gadwal', value: 'Jogulamba Gadwal' },
  { name: 'Kamareddy', value: 'Kamareddy' },
  { name: 'Karimnagar', value: 'Karimnagar' },
  { name: 'Khammam', value: 'Khammam' },
  { name: 'Kumuram Bheem', value: 'Kumuram Bheem' },
  { name: 'Mahabubabad', value: 'Mahabubabad' },
  { name: 'Mahabubnagar', value: 'Mahabubnagar' },
  { name: 'Mancherial', value: 'Mancherial' },
  { name: 'Medak', value: 'Medak' },
  { name: 'Medchal', value: 'Medchal' },
  { name: 'Mulugu', value: 'Mulugu' },
  { name: 'Nagarkurnool', value: 'Nagarkurnool' },
  { name: 'Nalgonda', value: 'Nalgonda' },
  { name: 'Narayanpet', value: 'Narayanpet' },
  { name: 'Nirmal', value: 'Nirmal' },
  { name: 'Nizamabad', value: 'Nizamabad' },
  { name: 'Peddapalli', value: 'Peddapalli' },
  { name: 'Rajanna Sircilla', value: 'Rajanna Sircilla' },
  { name: 'Rangareddy', value: 'Rangareddy' },
  { name: 'Sangareddy', value: 'Sangareddy' },
  { name: 'Siddipet', value: 'Siddipet' },
  { name: 'Suryapet', value: 'Suryapet' },
  { name: 'Vikarabad', value: 'Vikarabad' },
  { name: 'Wanaparthy', value: 'Wanaparthy' },
  { name: 'Warangal (Rural)', value: 'Warangal (Rural)' },
  { name: 'Warangal (Urban)', value: 'Warangal (Urban)' },
  { name: 'Yadadri Bhuvanagiri', value: 'Yadadri Bhuvanagiri' },
];

export const Tripura = [
  // { name: '*Tripura', value: '*Tripura' },
  { name: 'district*', value: 'district*' },
  { name: 'Dhalai', value: 'Dhalai' },
  { name: 'Gomati', value: 'Gomati' },
  { name: 'Khowai', value: 'Khowai' },
  { name: 'North Tripura', value: 'North Tripura' },
  { name: 'Sepahijala', value: 'Sepahijala' },
  { name: 'South Tripura', value: 'South Tripura' },
  { name: 'Unakoti', value: 'Unakoti' },
  { name: 'West Tripura', value: 'West Tripura' },
];

export const Uttarakhand = [
  // { name: '*Uttarakhand', value: '*Uttarakhand' },
  { name: 'district*', value: 'district*' },
  { name: 'Almora', value: 'Almora' },
  { name: 'Bageshwar', value: 'Bageshwar' },
  { name: 'Chamoli', value: 'Chamoli' },
  { name: 'Champawat', value: 'Champawat' },
  { name: 'Dehradun', value: 'Dehradun' },
  { name: 'Haridwar', value: 'Haridwar' },
  { name: 'Nainital', value: 'Nainital' },
  { name: 'Pauri Garhwal', value: 'Pauri Garhwal' },
  { name: 'Pithoragarh', value: 'Pithoragarh' },
  { name: 'Rudraprayag', value: 'Rudraprayag' },
  { name: 'Tehri Garhwal', value: 'Tehri Garhwal' },
  { name: 'Udham Singh Nagar', value: 'Udham Singh Nagar' },
  { name: 'Uttarkashi', value: 'Uttarkashi' },
];

export const UttarPradesh = [
  // { name: '*Uttar Pradesh', value: '*Uttar Pradesh' },
  { name: 'district*', value: 'district*' },
  { name: 'Agra', value: 'Agra' },
  { name: 'Aligarh', value: 'Aligarh' },
  { name: 'Ambedkar Nagar', value: 'Ambedkar Nagar' },
  { name: 'Amethi', value: 'Amethi' },
  { name: 'Amroha', value: 'Amroha' },
  { name: 'Auraiya', value: 'Auraiya' },
  { name: 'Ayodhya', value: 'Ayodhya' },
  { name: 'Azamgarh', value: 'Azamgarh' },
  { name: 'Baghpat', value: 'Baghpat' },
  { name: 'Bahraich', value: 'Bahraich' },
  { name: 'Ballia', value: 'Ballia' },
  { name: 'Balrampur', value: 'Balrampur' },
  { name: 'Banda', value: 'Banda' },
  { name: 'Barabanki', value: 'Barabanki' },
  { name: 'Bareilly', value: 'Bareilly' },
  { name: 'Basti', value: 'Basti' },
  { name: 'Bhadohi', value: 'Bhadohi' },
  { name: 'Bijnor', value: 'Bijnor' },
  { name: 'Budaun', value: 'Budaun' },
  { name: 'Bulandshahar', value: 'Bulandshahar' },
  { name: 'Chandauli', value: 'Chandauli' },
  { name: 'Chitrakoot', value: 'Chitrakoot' },
  { name: 'Deoria', value: 'Deoria' },
  { name: 'Etah', value: 'Etah' },
  { name: 'Etawah', value: 'Etawah' },
  { name: 'Farrukhabad', value: 'Farrukhabad' },
  { name: 'Fatehpur', value: 'Fatehpur' },
  { name: 'Firozabad', value: 'Firozabad' },
  { name: 'Gautam Buddha Nagar', value: 'Gautam Buddha Nagar' },
  { name: 'Ghaziabad', value: 'Ghaziabad' },
  { name: 'Ghazipur', value: 'Ghazipur' },
  { name: 'Gonda', value: 'Gonda' },
  { name: 'Gorakhpur', value: 'Gorakhpur' },
  { name: 'Hamirpur', value: 'Hamirpur' },
  { name: 'Hapur', value: 'Hapur' },
  { name: 'Hardoi', value: 'Hardoi' },
  { name: 'Hathras', value: 'Hathras' },
  { name: 'Jalaun', value: 'Jalaun' },
  { name: 'Jaunpur', value: 'Jaunpur' },
  { name: 'Jhansi', value: 'Jhansi' },
  { name: 'Kannauj', value: 'Kannauj' },
  { name: 'Kanpur Dehat', value: 'Kanpur Dehat' },
  { name: 'Kanpur Nagar', value: 'Kanpur Nagar' },
  { name: 'Kasganj', value: 'Kasganj' },
  { name: 'Kaushambi', value: 'Kaushambi' },
  { name: 'Kushi Nagar', value: 'Kushi Nagar' },
  { name: 'Lakhimpur Kheri', value: 'Lakhimpur Kheri' },
  { name: 'Lalitpur', value: 'Lalitpur' },
  { name: 'Lucknow', value: 'Lucknow' },
  { name: 'Maharajganj', value: 'Maharajganj' },
  { name: 'Mahoba', value: 'Mahoba' },
  { name: 'Mainpuri', value: 'Mainpuri' },
  { name: 'Mathura', value: 'Mathura' },
  { name: 'Mau', value: 'Mau' },
  { name: 'Meerut', value: 'Meerut' },
  { name: 'Mirzapur', value: 'Mirzapur' },
  { name: 'Moradabad', value: 'Moradabad' },
  { name: 'Muzaffar Nagar', value: 'Muzaffar Nagar' },
  { name: 'Pilibhit', value: 'Pilibhit' },
  { name: 'Pratapgarh', value: 'Pratapgarh' },
  { name: 'RaeBareli', value: 'RaeBareli' },
  { name: 'Rampur', value: 'Rampur' },
  { name: 'Saharanpur', value: 'Saharanpur' },
  { name: 'Sambhal', value: 'Sambhal' },
  { name: 'Sant Kabir Nagar', value: 'Sant Kabir Nagar' },
  { name: 'Shahjahanpur', value: 'Shahjahanpur' },
  { name: 'Shamali', value: 'Shamali' },
  { name: 'Shravasti', value: 'Shravasti' },
  { name: 'Siddharth Nagar', value: 'Siddharth Nagar' },
  { name: 'Sitapur', value: 'Sitapur' },
  { name: 'Sonbhadra', value: 'Sonbhadra' },
  { name: 'Sultanpur', value: 'Sultanpur' },
  { name: 'Unnao', value: 'Unnao' },
  { name: 'Varanasi', value: 'Varanasi' },
];

export const WestBengal = [
  // { name: '*West Bengal', value: '*West Bengal' },
  { name: 'district*', value: 'district*' },
  { name: 'Alipurduar', value: 'Alipurduar' },
  { name: 'Bankura', value: 'Bankura' },
  { name: 'Birbhum', value: 'Birbhum' },
  { name: 'Cooch Behar', value: 'Cooch Behar' },
  { name: 'Darjeeling', value: 'Darjeeling' },
  { name: 'East Medinipur (Purba Medinipur)', value: 'East Medinipur (Purba Medinipur)' },
  { name: 'Hooghly', value: 'Hooghly' },
  { name: 'Howrah', value: 'Howrah' },
  { name: 'Jalpaiguri', value: 'Jalpaiguri' },
  { name: 'Jhargram', value: 'Jhargram' },
  { name: 'Kalimpong', value: 'Kalimpong' },
  { name: 'Kolkata', value: 'Kolkata' },
  { name: 'Malda', value: 'Malda' },
  { name: 'Murshidabad', value: 'Murshidabad' },
  { name: 'Nadia', value: 'Nadia' },
  { name: 'North 24 Parganas', value: 'North 24 Parganas' },
  { name: 'North Dinajpur (Uttar Dinajpur)', value: 'North Dinajpur (Uttar Dinajpur)' },
  { name: 'Paschim Bardhaman', value: 'Paschim Bardhaman' },
  { name: 'Purba Bardhaman', value: 'Purba Bardhaman' },
  { name: 'Purulia', value: 'Purulia' },
  { name: 'South 24 Parganas', value: 'South 24 PargWest Medinipur (Paschim Medinipur)anas' },
  { name: 'South Dinajpur (Dakshin Dinajpur)', value: 'South Dinajpur (Dakshin Dinajpur)' },
  { name: 'West Medinipur (Paschim Medinipur)', value: 'West Medinipur (Paschim Medinipur)' },
];
